export const githubPrefix: string = 'GITHUB'

export enum GithubConstants {
  GITHUB_SEARCH_START = 'GITHUB_SEARCH_START',
  GITHUB_SEARCH_STOP = 'GITHUB_SEARCH_STOP',
  GITHUB_SEARCH_ERROR = 'GITHUB_SEARCH_ERROR',
}
