export const githubPrefix: string = 'GITHUB';

export enum GithubConstants {
  GITHUB_SEARCH_USERS_START = 'GITHUB_SEARCH_USERS_START',
  GITHUB_SEARCH_USERS_STOP = 'GITHUB_SEARCH_USERS_STOP',
  GITHUB_SEARCH_USERS_ERROR = 'GITHUB_SEARCH_USERS_ERROR',
  GITHUB_SEARCH_USERS_RESET = 'GITHUB_SEARCH_USERS_RESET',
  GITHUB_DUPLICATE_USERS = 'GITHUB_DUPLICATE_USERS',
  GITHUB_DELETE_USERS = 'GITHUB_DELETE_USERS',
}
